"""
Stock Recommender -- daily email with 10 stocks worth learning about.

Pulls recent news from major market ETFs and sectors, then asks Claude
to recommend 10 stocks based on what is moving in the market that day.

Usage:
  python3 stock_recommender.py           # print to terminal
  python3 stock_recommender.py --email   # print + email
"""

import os
import sys
import smtplib
import anthropic
from datetime import datetime
from email.message import EmailMessage
from fetch_stock_data import fetch_stock_data

# Broad set of tickers to pull news from -- covers major indices and sectors
NEWS_SOURCES = [
    "SPY", "QQQ", "IWM",   # broad market
    "XLK", "XLF", "XLE",   # tech, financials, energy
    "XLV", "XLY", "XLI",   # health, consumer, industrials
    "GLD", "TLT", "VIX",   # macro signals
]


def gather_news() -> str:
    """Pull headlines from across the market and format for Claude."""
    print("Gathering market news...\n")
    all_headlines = []

    for ticker in NEWS_SOURCES:
        try:
            data = fetch_stock_data(ticker)
            price = data["price"]
            change_str = "flat"
            if price["change_pct"] is not None:
                direction = "up" if price["change_pct"] >= 0 else "down"
                change_str = direction + " " + str(abs(price["change_pct"])) + "%"

            for article in data["news"][:2]:
                all_headlines.append(
                    "[" + ticker + " " + change_str + "] " + article["title"] + " (" + article["source"] + ", " + article["date"] + ")"
                )
            print("  " + ticker + " -- " + str(len(data["news"])) + " headlines collected")
        except Exception as e:
            print("  " + ticker + " -- skipped: " + str(e))

    return "\n".join(all_headlines)


def get_recommendations(headlines: str) -> str:
    """Ask Claude to recommend 10 stocks based on the news."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("\nANTHROPIC_API_KEY is not set.")
        sys.exit(1)

    today = datetime.now().strftime("%B %d, %Y")

    prompt = (
        "You are a stock market educator helping a beginner investor learn about the market.\n\n"
        "Today is " + today + ". Here are today's market headlines:\n\n"
        + headlines
        + "\n\nBased on these headlines and current market conditions, recommend exactly 10 stocks "
        "worth learning about today. For each stock include:\n\n"
        "- Ticker and company name\n"
        "- Sector\n"
        "- Why it is relevant today (1-2 sentences tied to the news)\n"
        "- One key thing a beginner should understand about this company\n"
        "- Risk level: Low / Medium / High\n\n"
        "Aim for variety across sectors. Mix well-known names with a few lesser-known ones. "
        "Format each stock clearly and number them 1-10. "
        "Do not add any closing notes or disclaimers after stock 10."
    )

    client = anthropic.Anthropic(api_key=api_key)
    report_parts = []

    with client.messages.stream(
        model="claude-opus-4-8",
        max_tokens=4096,
        thinking={"type": "adaptive"},
        messages=[{"role": "user", "content": prompt}],
    ) as stream:
        for text in stream.text_stream:
            print(text, end="", flush=True)
            report_parts.append(text)

    return "".join(report_parts)


def send_email(report: str):
    """Email the recommendations via Gmail."""
    gmail_user = os.environ.get("GMAIL_ADDRESS")
    gmail_password = os.environ.get("GMAIL_APP_PASSWORD")

    if not gmail_user or not gmail_password:
        print("\nSkipping email -- GMAIL_ADDRESS or GMAIL_APP_PASSWORD not set.")
        return

    gmail_password = gmail_password.replace("\xa0", " ").strip()
    clean_report = report.encode("ascii", errors="replace").decode("ascii")
    date_str = datetime.now().strftime("%B %d, %Y")

    body = (
        "Your Daily Stock Watchlist - " + date_str + "\n\n"
        "10 stocks worth learning about today, picked by your Macro Agent based on market news.\n\n"
        + clean_report
        + "\n\n---\nGenerated by Stock Recommender - claude-opus-4-8"
    )

    msg = EmailMessage()
    msg["Subject"] = "Daily Stock Watchlist - " + date_str
    msg["From"] = gmail_user
    msg["To"] = gmail_user
    msg.set_content(body)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_user, gmail_password)
            server.send_message(msg)
        print("\nWatchlist emailed to " + gmail_user)
    except Exception as e:
        print("\nEmail failed: " + str(e))


def run():
    send_to_email = "--email" in sys.argv[1:]

    print("\n" + "=" * 60)
    print("  STOCK RECOMMENDER -- Daily Watchlist")
    print("=" * 60 + "\n")

    headlines = gather_news()

    print("\nAsking Claude for today's top 10 stocks...\n")
    print("=" * 60 + "\n")

    report = get_recommendations(headlines)

    print("\n\n" + "=" * 60)
    print("  Recommendations generated by claude-opus-4-8")
    print("=" * 60 + "\n")

    if send_to_email:
        send_email(report)


if __name__ == "__main__":
    run()
